/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.airavata.userapi;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class UserAPIConstants {

  public static final String USER_API_VERSION = "0.12.0";

}
