/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.airavata.userapi.error;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.TException;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import javax.annotation.Generated;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * This exception is thrown by Airavata UserAPI Services when a call fails as a result of
 * a problem in the service that could not be changed through client's action.
 * 
 * airavataErrorType:  The message type indicating the error that occurred.
 *   must be one of the values of UserAPIErrorType.
 * 
 * message:  This may contain additional information about the error
 * 
 */
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2014-6-13")
public class UserAPISystemException extends TException implements org.apache.thrift.TBase<UserAPISystemException, UserAPISystemException._Fields>, java.io.Serializable, Cloneable, Comparable<UserAPISystemException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserAPISystemException");

  private static final org.apache.thrift.protocol.TField USER_APIERROR_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("userAPIErrorType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("message", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UserAPISystemExceptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UserAPISystemExceptionTupleSchemeFactory());
  }

  /**
   * 
   * @see UserAPIErrorType
   */
  public UserAPIErrorType userAPIErrorType; // required
  public String message; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see UserAPIErrorType
     */
    USER_APIERROR_TYPE((short)1, "userAPIErrorType"),
    MESSAGE((short)2, "message");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_APIERROR_TYPE
          return USER_APIERROR_TYPE;
        case 2: // MESSAGE
          return MESSAGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.MESSAGE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_APIERROR_TYPE, new org.apache.thrift.meta_data.FieldMetaData("userAPIErrorType", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, UserAPIErrorType.class)));
    tmpMap.put(_Fields.MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("message", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserAPISystemException.class, metaDataMap);
  }

  public UserAPISystemException() {
  }

  public UserAPISystemException(
    UserAPIErrorType userAPIErrorType)
  {
    this();
    this.userAPIErrorType = userAPIErrorType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserAPISystemException(UserAPISystemException other) {
    if (other.isSetUserAPIErrorType()) {
      this.userAPIErrorType = other.userAPIErrorType;
    }
    if (other.isSetMessage()) {
      this.message = other.message;
    }
  }

  public UserAPISystemException deepCopy() {
    return new UserAPISystemException(this);
  }

  @Override
  public void clear() {
    this.userAPIErrorType = null;
    this.message = null;
  }

  /**
   * 
   * @see UserAPIErrorType
   */
  public UserAPIErrorType getUserAPIErrorType() {
    return this.userAPIErrorType;
  }

  /**
   * 
   * @see UserAPIErrorType
   */
  public UserAPISystemException setUserAPIErrorType(UserAPIErrorType userAPIErrorType) {
    this.userAPIErrorType = userAPIErrorType;
    return this;
  }

  public void unsetUserAPIErrorType() {
    this.userAPIErrorType = null;
  }

  /** Returns true if field userAPIErrorType is set (has been assigned a value) and false otherwise */
  public boolean isSetUserAPIErrorType() {
    return this.userAPIErrorType != null;
  }

  public void setUserAPIErrorTypeIsSet(boolean value) {
    if (!value) {
      this.userAPIErrorType = null;
    }
  }

  public String getMessage() {
    return this.message;
  }

  public UserAPISystemException setMessage(String message) {
    this.message = message;
    return this;
  }

  public void unsetMessage() {
    this.message = null;
  }

  /** Returns true if field message is set (has been assigned a value) and false otherwise */
  public boolean isSetMessage() {
    return this.message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.message = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER_APIERROR_TYPE:
      if (value == null) {
        unsetUserAPIErrorType();
      } else {
        setUserAPIErrorType((UserAPIErrorType)value);
      }
      break;

    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_APIERROR_TYPE:
      return getUserAPIErrorType();

    case MESSAGE:
      return getMessage();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_APIERROR_TYPE:
      return isSetUserAPIErrorType();
    case MESSAGE:
      return isSetMessage();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserAPISystemException)
      return this.equals((UserAPISystemException)that);
    return false;
  }

  public boolean equals(UserAPISystemException that) {
    if (that == null)
      return false;

    boolean this_present_userAPIErrorType = true && this.isSetUserAPIErrorType();
    boolean that_present_userAPIErrorType = true && that.isSetUserAPIErrorType();
    if (this_present_userAPIErrorType || that_present_userAPIErrorType) {
      if (!(this_present_userAPIErrorType && that_present_userAPIErrorType))
        return false;
      if (!this.userAPIErrorType.equals(that.userAPIErrorType))
        return false;
    }

    boolean this_present_message = true && this.isSetMessage();
    boolean that_present_message = true && that.isSetMessage();
    if (this_present_message || that_present_message) {
      if (!(this_present_message && that_present_message))
        return false;
      if (!this.message.equals(that.message))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_userAPIErrorType = true && (isSetUserAPIErrorType());
    list.add(present_userAPIErrorType);
    if (present_userAPIErrorType)
      list.add(userAPIErrorType.getValue());

    boolean present_message = true && (isSetMessage());
    list.add(present_message);
    if (present_message)
      list.add(message);

    return list.hashCode();
  }

  @Override
  public int compareTo(UserAPISystemException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUserAPIErrorType()).compareTo(other.isSetUserAPIErrorType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserAPIErrorType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userAPIErrorType, other.userAPIErrorType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMessage()).compareTo(other.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.message, other.message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserAPISystemException(");
    boolean first = true;

    sb.append("userAPIErrorType:");
    if (this.userAPIErrorType == null) {
      sb.append("null");
    } else {
      sb.append(this.userAPIErrorType);
    }
    first = false;
    if (isSetMessage()) {
      if (!first) sb.append(", ");
      sb.append("message:");
      if (this.message == null) {
        sb.append("null");
      } else {
        sb.append(this.message);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (userAPIErrorType == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'userAPIErrorType' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserAPISystemExceptionStandardSchemeFactory implements SchemeFactory {
    public UserAPISystemExceptionStandardScheme getScheme() {
      return new UserAPISystemExceptionStandardScheme();
    }
  }

  private static class UserAPISystemExceptionStandardScheme extends StandardScheme<UserAPISystemException> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserAPISystemException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_APIERROR_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.userAPIErrorType = UserAPIErrorType.findByValue(iprot.readI32());
              struct.setUserAPIErrorTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.message = iprot.readString();
              struct.setMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserAPISystemException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.userAPIErrorType != null) {
        oprot.writeFieldBegin(USER_APIERROR_TYPE_FIELD_DESC);
        oprot.writeI32(struct.userAPIErrorType.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.message != null) {
        if (struct.isSetMessage()) {
          oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
          oprot.writeString(struct.message);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserAPISystemExceptionTupleSchemeFactory implements SchemeFactory {
    public UserAPISystemExceptionTupleScheme getScheme() {
      return new UserAPISystemExceptionTupleScheme();
    }
  }

  private static class UserAPISystemExceptionTupleScheme extends TupleScheme<UserAPISystemException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserAPISystemException struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.userAPIErrorType.getValue());
      BitSet optionals = new BitSet();
      if (struct.isSetMessage()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMessage()) {
        oprot.writeString(struct.message);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserAPISystemException struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.userAPIErrorType = UserAPIErrorType.findByValue(iprot.readI32());
      struct.setUserAPIErrorTypeIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.message = iprot.readString();
        struct.setMessageIsSet(true);
      }
    }
  }

}

